// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxvisoljndezewhdobea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dmlzb2xqbmRlemV3aGRvYmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjI1MzMsImV4cCI6MjA2NTEzODUzM30.ZAsGZ2mubjOOmUKzVWaRyIzcg4AFjMcP7nuCEKv3ATs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);